CREATE USER daniel WITH ENCRYPTED PASSWORD 'parola';
GRANT ALL PRIVILEGES ON DATABASE pizza_point TO daniel ;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO daniel;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO daniel;